/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senai.view;

import br.com.senai.DAO.DAO;
import br.com.senai.modelo.Adm;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;

/**
 *
 * @author Aluno
 */
public class AdmLoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdmLoginFrame
     */
    public AdmLoginFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNorte = new JPanel();
        jLabelTitulo = new JLabel();
        jPanelCentro = new JPanel();
        jPanelLogin = new JPanel();
        jLabelNome = new JLabel();
        jTextFieldNome = new JTextField();
        jLabelSenha = new JLabel();
        jPasswordField = new JPasswordField();
        jPanelSul = new JPanel();
        jButtonLogin = new JButton();
        jButtonVoltar = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrar");
        setMaximumSize(new Dimension(800, 600));
        setMinimumSize(new Dimension(800, 600));
        setPreferredSize(new Dimension(800, 600));
        setResizable(false);

        jLabelTitulo.setFont(new Font("Calibri", 1, 24)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(SwingConstants.CENTER);
        jLabelTitulo.setText("Login");
        jLabelTitulo.setHorizontalTextPosition(SwingConstants.CENTER);

        GroupLayout jPanelNorteLayout = new GroupLayout(jPanelNorte);
        jPanelNorte.setLayout(jPanelNorteLayout);
        jPanelNorteLayout.setHorizontalGroup(jPanelNorteLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNorteLayout.createSequentialGroup()
                .addContainerGap(365, Short.MAX_VALUE)
                .addComponent(jLabelTitulo, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(365, Short.MAX_VALUE))
        );
        jPanelNorteLayout.setVerticalGroup(jPanelNorteLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNorteLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabelTitulo)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelNorte, BorderLayout.NORTH);

        jPanelLogin.setLayout(new GridLayout(4, 1));

        jLabelNome.setText("Nome");
        jLabelNome.setVerticalAlignment(SwingConstants.BOTTOM);
        jPanelLogin.add(jLabelNome);

        jTextFieldNome.setText("adm");
        jTextFieldNome.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });
        jPanelLogin.add(jTextFieldNome);

        jLabelSenha.setText("Senha");
        jLabelSenha.setVerticalAlignment(SwingConstants.BOTTOM);
        jPanelLogin.add(jLabelSenha);

        jPasswordField.setText("1234");
        jPanelLogin.add(jPasswordField);

        GroupLayout jPanelCentroLayout = new GroupLayout(jPanelCentro);
        jPanelCentro.setLayout(jPanelCentroLayout);
        jPanelCentroLayout.setHorizontalGroup(jPanelCentroLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanelCentroLayout.createSequentialGroup()
                .addContainerGap(255, Short.MAX_VALUE)
                .addComponent(jPanelLogin, GroupLayout.PREFERRED_SIZE, 280, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(265, Short.MAX_VALUE))
        );
        jPanelCentroLayout.setVerticalGroup(jPanelCentroLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanelCentroLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelLogin, GroupLayout.PREFERRED_SIZE, 181, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelCentro, BorderLayout.CENTER);

        jPanelSul.setPreferredSize(new Dimension(800, 80));

        jButtonLogin.setFont(new Font("sansserif", 1, 14)); // NOI18N
        jButtonLogin.setText("Logar");
        jButtonLogin.setHorizontalTextPosition(SwingConstants.CENTER);
        jButtonLogin.setPreferredSize(new Dimension(73, 40));
        jButtonLogin.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jButtonVoltar.setFont(new Font("sansserif", 1, 14)); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.setHorizontalTextPosition(SwingConstants.CENTER);
        jButtonVoltar.setPreferredSize(new Dimension(73, 40));
        jButtonVoltar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        GroupLayout jPanelSulLayout = new GroupLayout(jPanelSul);
        jPanelSul.setLayout(jPanelSulLayout);
        jPanelSulLayout.setHorizontalGroup(jPanelSulLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSulLayout.createSequentialGroup()
                .addContainerGap(281, Short.MAX_VALUE)
                .addComponent(jButtonVoltar, GroupLayout.PREFERRED_SIZE, 116, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLogin, GroupLayout.PREFERRED_SIZE, 116, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(281, Short.MAX_VALUE))
        );
        jPanelSulLayout.setVerticalGroup(jPanelSulLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSulLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelSulLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLogin, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVoltar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelSul, BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        this.dispose();
        MenuFrame menu = new MenuFrame();
        menu.setVisible(true);
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonLoginActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        Adm adm = new Adm(jTextFieldNome.getText(), jPasswordField.getText());

        if (DAO.logarAdm(adm)) {

            GerPerguntaFrame gerPerguntaFrame = new GerPerguntaFrame();
            this.dispose();
            gerPerguntaFrame.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Usuário ou senha incorreta", "Erro",  JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jTextFieldNomeActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButtonLogin;
    private JButton jButtonVoltar;
    private JLabel jLabelNome;
    private JLabel jLabelSenha;
    private JLabel jLabelTitulo;
    private JPanel jPanelCentro;
    private JPanel jPanelLogin;
    private JPanel jPanelNorte;
    private JPanel jPanelSul;
    private JPasswordField jPasswordField;
    private JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
